### ISSUE TITLE
Tray is not working in demo

### ISSUE THREAD

**Issue by MarcusAllen605** [ElectronNET/electron.net-api-demos#15]
The Tray window seems to be throwing a Javascript exception everytime I press it. 

![electronnetrayerror](https://user-images.githubusercontent.com/37712424/54036870-ad484e00-418a-11e9-8a53-71023731ab77.PNG)

**Comment by LeatonChuter** [comment]
I'm seeing the same problem, I've tried passing the absolute path to the icon image to no avail.

**Comment by GregorBiswanger** [comment]
How did you the application start? As exe or via the Electron.NET CLI "`electronize start`"?

**Comment by danipen** [comment]
Same issue here. I started the application using `"electronize start"`.

**Comment by danipen** [comment]
The issue comes from the icon name, that is malformed. In file:

C:\Users\dani_\gitrepos\electron.net-api-demos\obj\Host\api\tray.js, line 55

`        const imagePath = path.join(__dirname.replace('api', ''), 'bin', image);`

The dirname contains the word "api", so the fullpath to the icon is malformed.

**Comment by GregorBiswanger** [comment]
Updated to .NET Core 3.1 and Electron.NET 8.31.1.

Works now...
